name: Build Android APK

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build APK with Buildozer Action
        uses: diground/buildozer-action@v1
        with:
          workdir: '.'
          buildozer_version: 'stable'

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ClinicApp-APK
          path: bin/*.apk
          
